### ISSUE TITLE
Missing 2-structured-data folder, settings.yml.dist file

### ISSUE THREAD

**Issue by noam8080** [GoogleCloudPlatform/getting-started-php#213]
The getting started instructions on google say:
https://cloud.google.com/php/getting-started/using-cloud-datastore

> Go to the getting-started-php/2-structured-data directory, and copy the settings.yml.dist file:
> cp config/settings.yml.dist config/settings.yml

Can't find here the 2-structured-data folder or the settings.yml.dist file
Am I missing something?
thanks

**Comment by isaque21** [comment]
I also didn't find that folder.
Any solution?

**Comment by isaque21** [comment]
I just found it here:

https://github.com/GoogleCloudPlatform/getting-started-php/tree/steps/2-structured-data

Apparently, in another repository.

**Comment by noam8080** [comment]
Thanks,
I found it too eventually
But Google's tutorial didn't match the repository, and I couldn't just follow the steps, and actually couldn't get PHP to work with MongoDB, and eventually I just had to just build everything in NodeJS instead of PHP
Thanks again

**Comment by bshaffer** [comment]
The tutorial referenced in the initial bug has been removed, which is why the steps for it were moved out of the master branch. Please use the [datastore quickstart](https://cloud.google.com/datastore/docs/reference/libraries), or follow the tutorial on [Handling sessions with Firestore](https://cloud.google.com/php/getting-started/session-handling-with-firestore)! And please let us know how you feel about those resources!

Thanks!
